=== j1m5s3/circle-solutions-eng-tech-assesment/card-api-json-req/api-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "billingDetails": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "line1": {
            "type": "string"
          },
          "district": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "city",
          "country",
          "postalCode",
          "line1",
          "district"
        ]
      },
      "metadata": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "sessionId": {
            "type": "string",
            "minLength": 10
          },
          "ipAddress": {
            "type": "string"
          }
        },
        "required": [
          "email",
          "sessionId",
          "ipAddress"
        ]
      },
      "idempotencyKey": {
        "type": "string",
        "format": "uuid"
      },
      "keyId": {
        "type": "string"
      },
      "encryptedData": {
        "type": "string"
      },
      "expMonth": {
        "type": "integer"
      },
      "expYear": {
        "type": "integer"
      }
    },
    "required": [
      "billingDetails",
      "metadata",
      "idempotencyKey",
      "keyId",
      "encryptedData",
      "expMonth",
      "expYear"
    ]
  }

=== j1m5s3/circle-solutions-eng-tech-assesment/card-api-json-req/201-json-req.json
{
    "billingDetails": {
      "name": "Satoshi Nakamoto",
      "city": "Braintree",
      "country": "US",
      "postalCode": "02184",
      "line1": "100 Money Street",
      "district": "MA"
    },
    "metadata": {
      "email": "james.lynch.uml@gmail.com",
      "sessionId": "DE6FA86F60BB47B379307F851E238617",
      "ipAddress": "244.28.239.130"
    },
    "idempotencyKey": "ba943ff1-ca16-49b2-ba55-1057e70ca5c7",
    "keyId": "key1",
    "encryptedData": "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgp3Y0JNQTBYV1NGbEZScFZoQVFmL2J2bVVkNG5LZ3dkbExKVTlEdEFEK0p5c0VOTUxuOUlRUWVGWnZJUWEKMGgzQklpRFNRU0RMZmI0NEs2SXZMeTZRbm54bmFLcWx0MjNUSmtPd2hGWFIrdnNSMU5IbnVHN0lUNWJECmZzeVdleXlNK1JLNUVHV0thZ3NmQ2tWamh2NGloY29xUnlTTGtJbWVmRzVaR0tMRkJTTTBsTFNPWFRURQpiMy91eU1zMVJNb3ZiclNvbXkxa3BybzUveWxabWVtV2ZsU1pWQlhNcTc1dGc1YjVSRVIraXM5ckc0cS8KMXl0M0FOYXA3UDhKekFhZVlyTnVNZGhGZFhvK0NFMC9CQnN3L0NIZXdhTDk4SmRVUEV0NjA5WFRHTG9kCjZtamY0YUtMQ01xd0RFMkNVb3dPdE8vMzVIMitnVDZKS3FoMmtjQUQyaXFlb3luNWcralRHaFNyd3NKWgpIdEphQWVZZXpGQUVOaFo3Q01IOGNsdnhZVWNORnJuNXlMRXVGTkwwZkczZy95S3loclhxQ0o3UFo5b3UKMFVxQjkzQURKWDlJZjRBeVQ2bU9MZm9wUytpT2lLall4bG1NLzhlVWc3OGp1OVJ5T1BXelhyTzdLWTNHClFSWm8KPXc1dEYKLS0tLS1FTkQgUEdQIE1FU1NBR0UtLS0tLQo",
    "expMonth": 1,
    "expYear": 2020
}
